name: Build for debug
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.10.0

    - name: Install dependencies
      run: npm install

    - name: Create .env (environment variables file)
      run: >
        node --loader ts-node/esm .github/createEnviron.ts
        --NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}
        --NOTION_DATABASE_ID=${{ secrets.NOTION_TOKEN }}

    - name: Build app for testing
      run: npm run build

    - uses: actions/upload-artifact@v4
      with:
        name: exported
        path: out/
